### PR TITLE
style py installed

### PR DESCRIPTION
**Pull request by vignesh4v**
style py added

### CODE REVIEW

**Comment by ramsunvtech** [comment]
@vignesh4v nice changes, can u add screenshot for every files? Thx

**Comment by vignesh4v** [comment]
image

**Comment by vignesh4v** [comment]
image
image

image

image

image

image

image

image
image

**Comment by vignesh4v** [comment]
image
image
image

image

**Comment by vignesh4v** [comment]
Hi @ramsunvtech  - I have added screenshots for the files where I have added the stylepy library.

**Pull request merged**
